### ISSUE TITLE
Add support for RN 0.29

### ISSUE THREAD

**Issue by duranmla** [luggg/react-native-android-snackbar#14]
I have tried to do this by just removing the reference of the activity on the constructor and using `getCurrentActivity()` but I got an error that says: "undefined symbol" for that method, even when we are extended from `ReactContextBaseJavaModule` so, I'm not sure what is happening here, if I find the solution I will make the PR, otherwise, if someone knows what is happening will be great.

**Comment by jwarby** [comment]
Hey @duranmla, you could try my fork if you like: https://github.com/jwarby/react-native-android-snackbar.  I haven't got round to submitting a pull request back to this repo yet as I rushed out the changes so need to go back and make sure everything is being handled properly.  Seems to be working out OK for me so far though.  Will try to take a proper look this week and get a pull request submitted to @pedro.
