### ISSUE TITLE
actionLabel does not seem to work

### ISSUE THREAD

**Issue by zoontek** [luggg/react-native-android-snackbar#4]
Hello,

Just realize I can't force actionLabel text with react-native 0.21.
It stays at "DISMISS" whatever I do.

**Comment by Ehesp** [comment]
It does work, you need an actionLabel AND a actionCallback.

**Comment by zoontek** [comment]
@Ehesp Note the issue is from march 😁

**Comment by Ehesp** [comment]
Oh yeah haha... Oh well :D
