### ISSUE TITLE
Undefined is not a function (evaluating 'NativeSnackbar.dismiss()')

### ISSUE THREAD

**Issue by VinceBT** [luggg/react-native-android-snackbar#7]
``` jsx
let onCardPress = ((board) => {
  Snackbar.dismiss();
  this.props.navigator.push({name: 'BoardScene', data: {board: board}});
});
```

And it throws this error :(

```
Undefined is not a function (evaluating 'NativeSnackbar.dismiss()')
```

**Comment by pedro** [comment]
hmm odd, is this failing just for dismiss? Can you render a snackbar?

**Comment by VinceBT** [comment]
Snackbars render well and the custom action too.

**Comment by jwarby** [comment]
@VinceBT have you tried deleting the `android/build` directory before running `react-native run-android`?  I seem to remember having a similar problem when I was developing the dismiss functionality, and it was because my JS was up-to-date but my compiled Java wasn't.
