### ISSUE TITLE
Rnpm : new ReactSnackbarPackage(this)

### ISSUE THREAD

**Issue by VinceBT** [luggg/react-native-android-snackbar#9]
The command rnpm link for the package adds the line new ReactSnackbarPackage() but it doesn't compile.
I have to manually change the line to new ReactSnackbarPackage(this) everytime so it can compile.

**Comment by erickreutz** [comment]
Feel free to submit a pull-request!

**Comment by VinceBT** [comment]
I've been looking for a solution and I couldn't find any.
I think only you can fix it. It has to do with your rnpm configuration itself.

**Comment by pedro** [comment]
Fixed in master, release 0.1.0
